// src/server.js
import express from 'express';
import { WebSocketServer } from 'ws';
import http from 'node:http';
import path from 'node:path';
import fsp from 'node:fs/promises';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';
import { buildIndex, resolveSessionFile } from './sessionIndex.js';
import { parseAll } from './parser.js';
import { toMarkdown } from './exporter.js';
import { Watcher } from './watcher.js';
import { isValidSessionId } from './paths.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.join(__dirname, '..');
const PORT = process.env.PORT || 4567;
const HOST = '127.0.0.1'; // localhost only

// highlight.js/es/*.js are Node-only shims (they do `import from '../lib/*.js'` where
// lib/ is CJS). To serve a browser-importable ESM highlight.js, we generate a synthetic
// module at /vendor/highlight-es/highlight.js by evaluating the CJS sources server-side
// via require() and inlining all dependency sources into a Function()-wrapped bundle.
const _require = createRequire(import.meta.url);
const _fs = _require('fs');

function _buildHljsEsmBundle() {
  // Read each CJS file and inline it in dependency order with a shared _require shim.
  const libDir = path.join(ROOT, 'node_modules/highlight.js/lib');
  const coreSrc = _fs.readFileSync(path.join(libDir, 'core.js'), 'utf8');
  const commonSrc = _fs.readFileSync(path.join(libDir, 'common.js'), 'utf8');

  // Read all language sources referenced by common.js.
  const langMatches = [...commonSrc.matchAll(/require\(['"]\.\/languages\/([^'"]+)['"]\)/g)];
  const langSources = langMatches.map(([, name]) => {
    const src = _fs.readFileSync(path.join(libDir, 'languages', name + '.js'), 'utf8');
    return `__define(${JSON.stringify('./languages/' + name)}, function(require,module,exports){${src}});`;
  });

  return `// Auto-generated browser ESM bundle for highlight.js (vendored from node_modules)
// Generated by src/server.js at startup to avoid CJS in browser ESM imports.
const __cache = {};
function __define(id, factory) {
  const m = { exports: {} };
  factory(__require, m, m.exports);
  __cache[id] = m.exports;
}
function __require(id) {
  // Normalise relative ids.
  if (__cache[id] !== undefined) return __cache[id];
  // core.js is loaded first; common.js requires it as './core'.
  if (id === './core') return __cache['./core'];
  throw new Error('hljs-bundle: unresolved require: ' + id);
}
// 1. core
__define('./core', function(require,module,exports){${coreSrc}});
// 2. languages
${langSources.join('\n')}
// 3. common (registers all languages onto core)
__define('./common', function(require,module,exports){${commonSrc}});
const hljs = __cache['./common'];
export default hljs;
`;
}

let _hljsEsmBody;
try {
  _hljsEsmBody = _buildHljsEsmBundle();
} catch (e) {
  console.warn('highlight.js ESM bundle generation failed:', e.message);
  _hljsEsmBody = 'export default { highlightAuto: () => ({ value: "" }), listLanguages: () => [] };';
}

const app = express();
app.use(express.json());
app.use(express.static(path.join(ROOT, 'public')));
// Serve vendored frontend libs.
app.use('/vendor/marked', express.static(path.join(ROOT, 'node_modules/marked/lib')));
app.use('/vendor/highlight', express.static(path.join(ROOT, 'node_modules/highlight.js/styles')));
// Synthetic browser-compatible ESM highlight.js at the path render.js imports.
// node_modules/highlight.js/es/ has no highlight.js file — the actual entry is index.js,
// but that file only works in Node (it re-imports CJS lib/). This synthetic endpoint
// inlines all CJS sources with a Function()-wrapped require shim so the browser can use it.
app.get('/vendor/highlight-es/highlight.js', (_req, res) => {
  res.setHeader('Content-Type', 'application/javascript; charset=utf-8');
  res.send(_hljsEsmBody);
});

app.get('/api/sessions', async (req, res) => {
  res.json(await buildIndex());
});

app.get('/api/session/:id', async (req, res) => {
  const { id } = req.params;
  if (!isValidSessionId(id)) return res.status(400).json({ error: 'invalid session id' });
  const file = await resolveSessionFile(id);
  if (!file) return res.status(404).json({ error: 'session not found' });
  const text = await fsp.readFile(file, 'utf8');
  res.json({ id, messages: parseAll(text) });
});

app.post('/api/export', async (req, res) => {
  const { sessionId, uuids } = req.body || {};
  if (!isValidSessionId(sessionId)) return res.status(400).json({ error: 'invalid session id' });
  const file = await resolveSessionFile(sessionId);
  if (!file) return res.status(404).json({ error: 'session not found' });
  const text = await fsp.readFile(file, 'utf8');
  const md = toMarkdown(parseAll(text), Array.isArray(uuids) ? uuids : null);
  res.setHeader('Content-Type', 'text/markdown; charset=utf-8');
  res.setHeader('Content-Disposition', `attachment; filename="${sessionId}.md"`);
  res.send(md);
});

const server = http.createServer(app);
const wss = new WebSocketServer({ server, path: '/ws' });

wss.on('connection', (ws) => {
  const watcher = new Watcher();
  const subscriptions = new Set();

  const onAppend = ({ sessionId, messages }) => {
    if (ws.readyState === ws.OPEN) ws.send(JSON.stringify({ type: 'append', sessionId, messages }));
  };
  const onError = ({ sessionId, error }) => {
    if (ws.readyState === ws.OPEN) ws.send(JSON.stringify({ type: 'error', sessionId, error: String(error) }));
  };
  watcher.on('append', onAppend);
  watcher.on('error', onError);

  ws.on('message', async (raw) => {
    let msg;
    try { msg = JSON.parse(raw.toString()); } catch { return; }

    if (msg.subscribe && isValidSessionId(msg.subscribe)) {
      const id = msg.subscribe;
      if (subscriptions.has(id)) return;
      const file = await resolveSessionFile(id);
      if (!file) { ws.send(JSON.stringify({ type: 'error', sessionId: id, error: 'not found' })); return; }
      const buf = await fsp.readFile(file);
      ws.send(JSON.stringify({ type: 'history', sessionId: id, messages: parseAll(buf.toString('utf8')) }));
      subscriptions.add(id);
      await watcher.watch(id, file, buf.length); // tail resumes exactly where history ended
    }

    if (msg.unsubscribe && subscriptions.has(msg.unsubscribe)) {
      watcher.unwatch(msg.unsubscribe);
      subscriptions.delete(msg.unsubscribe);
    }
  });

  ws.on('close', () => {
    for (const id of subscriptions) watcher.unwatch(id);
    subscriptions.clear();
    watcher.removeAllListeners();
  });
});

server.listen(PORT, HOST, () => {
  console.log(`Claude Session Monitor: http://${HOST}:${PORT}`);
});
